spring:
  thymeleaf:
    cache: false
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: pubtrans
      jdbc-url: jdbc:mysql://192.168.110.12:3306/springbootdb?useUnicode=true&characterEncoding=utf8
#    secondary:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      jdbc-url: jdbc:mysql://localhost:53306/springbootdb2?useUnicode=true&characterEncoding=utf8
  data:
    mongodb:
      url: mongodb://192.168.110.12:27017
      database: pubtrans

  kafka:
    bootstrap-servers: 192.168.110.12:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 2000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      timeout: 60000
  #      # WebStatFilter配置
#    web-stat-filter:
#        enabled: true
#        # 添加过滤规则
#        url-pattern: /*
#        # 忽略过滤的格式
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

# StatViewServlet配置
#    stat-view-servlet:
#        enabled: true
#        # 访问路径为/druid时，跳转到StatViewServlet
#        url-pattern: /druid/*
#        # 是否能够重置数据
#        reset-enable: false
#        # 需要账号密码才能访问控制台
#        login-username: druid
#        login-password: druid123
#        # IP白名单
#        # allow: 127.0.0.1
#        #　IP黑名单（共同存在时，deny优先于allow）
#        # deny: 192.168.1.218
#
#      # 配置StatFilter
#    filter:
#        stat:
#          log-slow-sql: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
    password: 123456



mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  path: E:\\demo
  file: log\sp.log
  level:
    com:
      spring:
        learn:
          Dao: debug
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"

load.data: route
#  security:
#    enabled: false
#  server:
#    port: 9991
